### ISSUE TITLE
Try Finally block without an except block is not supported

### ISSUE THREAD

**Issue by Ecoral360** [FlyableDev/Flyable#67]
```py
try:
    print(int("abc"))
finally:
    print("End")
```
the error raised is an index out of range exception that occurs in the content_try.py file

Traceback (most recent call last):
  File "c:\...\Flyable\main.py", line 67, in <module>
    main("test.py", dir, "a")
  File "c:\...\Flyable\main.py", line 28, in main
    compiler.compile()
  File "c:\...\Flyable\flyable\compiler.py", line 35, in compile
    self.__parse()
  File "c:\...\Flyable\flyable\compiler.py", line 75, in __parse
    raise exception
  File "c:\...\Flyable\flyable\compiler.py", line 67, in __parse
    self.__main_impl = adapter.adapt_func(self.__data.get_file(0).get_global_func(), [], self.__data,
  File "c:\...\Flyable\flyable\parse\adapter.py", line 45, in adapt_func
    parser.parse_impl(adapted_impl)
  File "c:\...\Flyable\flyable\parse\parser.py", line 31, in parse_impl
    vis.parse()
  File "c:\...\Flyable\flyable\parse\parser_visitor.py", line 75, in parse
    self.visit(self.__func.get_parent_func().get_node().body)
  File "c:\...\Flyable\flyable\parse\parser_visitor.py", line 131, in visit
    super().visit(e)
  File "C:\...\Python\Python310\lib\ast.py", line 410, in visit
    return visitor(node)
  File "c:\...\Flyable\flyable\parse\parser_visitor.py", line 1137, in visit_Try
    content_try.parse_try(self, node)
  File "c:\...\Flyable\flyable\parse\content\content_try.py", line 20, in parse_try
    visitor.get_builder().br(handlers_cond_block[0])
IndexError: list index out of range

**Comment by ALavallee** [comment]
@MoSk3 @Ecoral360 This one is fixed right ?

**Comment by Ecoral360** [comment]
yes it is
